-- profile test sql
SELECT USERNAME,
	EMAIL,
	PASSWORD,
	PASSWORD,
	CREATE_DATE,
	IS_ACTIVE,
	AVATAR_URL,
	GENDER_TYPE
FROM USERS
LEFT JOIN PROFILE ON USERS.ID = PROFILE.USER_ID
LEFT JOIN GENDER_TYPE ON PROFILE.GENDER = GENDER_TYPE.ID